service : codecentric-sls-offline

plugins:
  - serverless-dynamodb-local
  - serverless-offline  # should be last in list

provider:
  name: aws
  runtime: nodejs12.x
  region: us-east-1
  environment:
    CONFIG_PERSONS_TABLE: ${self:custom.tableNames.persons}
    CONFIG_DYNAMODB_ENDPOINT: ${self:custom.endpoints.dynamodb-url}

custom :
  endpoints:
    dynamodb-url: 'http://localhost:8000'

  tableNames:
    persons: 'cc-persons'

  bucketNames:
    personsImages: 'cc-person-images'

  dynamodb:
    start:
      migrate: true # migrate ensures that the required DynamoDB tables are created automatically on start up.
    stages:
      - dev

functions :
  persons:
    timeout: 30
    handler: handler/persons.handler
    events:
      - http:
          path: /persons
          method: get
          cors: true
      - http:
          path: /persons
          method: post
          cors: true

resources:
  - ${file(resources/persons-table.yaml)}